services:
  - type: web
    name: nookfinder
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: eamqdjfo
      - key: CLOUDINARY_API_KEY
        value: "882323531432825"
      - key: CLOUDINARY_API_SECRET
        sync: false
